### ISSUE TITLE
Feature request: watch mode without clearing page

### ISSUE THREAD

**Issue by cbiertue** [wookayin/gpustat#108]
Hi, 
Can you change the way how the watch mode 'gpustat -i <time>' is displayed? I would prefer to have it appended to the current terminal output instead of clearing the page - i.e. in the same way as 'gpustat' is displayed. 
That would allow to see the previous terminal input as well as showing the last gpustat output after quitting the program. 
To me, it would also feel more natural instead of having a new page and after quitting to get back to the previous terminal display.

Thanks!

**Comment by wookayin** [comment]
I don't think changing the behavior of `gpustat -i` is a good idea but we can add another watch mode as described. But actually there is a very easy (alternative) way to do this:

```bash
while true; do gpustat; sleep 5; done
```

**Comment by wookayin** [comment]
Given there is a easy way with shell script, to make gpustat printed periodically without clearing the terminal, I will close this issue as unplanned. It'd be difficult to change the existing behavior of `-i`; we may add a new feature/mode, but since the behavior is not difficult to achieve this isn't be of a high priority.
