### ISSUE TITLE
Incorrect memory usage for nvidia driver higher than R510

### ISSUE THREAD

**Issue by huchinlp** [wookayin/gpustat#141]
When I update my nvidia driver to 515.76, `gpustat` always shows there are **308MB memory used** even no process using gpus.
But `nvidia-smi` shows there are **no memory being used**, so I am very confused...

Here is my environment:
ubuntu                18.04
gpustat               1.0.0
nvidia-driver       515.76
kernel                 4.15.0-171-generic

And here are the outputs of `nvidia-smi` and `gpustat`:
![nvidia-smi](https://user-images.githubusercontent.com/40781986/200163217-89bd18aa-0a50-4cc6-aa10-ffaecc299b2e.jpg)
![gpustat](https://user-images.githubusercontent.com/40781986/200163226-df7d6359-df57-4f62-b571-49bb03659a16.jpg)

**Comment by wookayin** [comment]
Before updating the driver was it fine? If so, can you please let me know of the driver version?

This is probably due to the mismatch between pynvml and nvidia driver version. We pinned nvidia-ml-py version at 11.495.46, this is not compatible with very recent drivers. Please see https://github.com/wookayin/gpustat/pull/107 for details. 

As a workaround, you can try installing nvidia-ml-py (it will complain about the incompatibility with gpustat v1.0.0) [to the latest release](https://pypi.org/project/nvidia-ml-py/#history), e.g. `pip install nvidia-ml-py>=11.515.75 --ignore-installed`. With this pynvml version, gpustat will not work with old nvidia drivers but it should be OK in your environments. Can you please let me know how the result would differ?

**Comment by wookayin** [comment]
@huchinlp Any comments?

**Comment by jinmingyi1998** [comment]
same problem.

307MB more than `nvidia-smi`
![image](https://user-images.githubusercontent.com/29097382/202355761-a5a5e497-373a-4381-85c7-ff6d832aef99.png)


i tried nvidia-ml-py==11.515.48  11.515.75

gpustat==1.0.0

environment is docker nvcr.io/nvidia/cuda:11.7.1-cudnn8-devel-ubuntu20.04

**Comment by wookayin** [comment]
@jinmingyi1998, Can you try [this](https://github.com/wookayin/gpustat/issues/141#issuecomment-1306696939)? With (temporarily) using `nvidia-ml-py>=11.515.75`, would the output be diffrent?

**Comment by wookayin** [comment]
Can you please try the following:

```python
import pynvml
pynvml.nvmlInit()
handle = pynvml.nvmlDeviceGetHandleByIndex(0)
print(pynvml.nvmlDeviceGetMemoryInfo(handle))
print(pynvml.nvmlDeviceGetMemoryInfo(handle, version=2))
```

It looks like `nvmlDeviceGetMemoryInfo_v2` was added in nvml 510.39.01.

**Comment by jinmingyi1998** [comment]
> Can you please try the following:
> 
> ```python
> import pynvml
> pynvml.nvmlInit()
> handle = pynvml.nvmlDeviceGetHandleByIndex(0)
> print(pynvml.nvmlDeviceGetMemoryInfo(handle))
> print(pynvml.nvmlDeviceGetMemoryInfo(handle, version=2))
> ```
> 
> It looks like `nvmlDeviceGetMemoryInfo_v2` was added in driver 510.39.01 or higher. Related to [XuehaiPan/nvitop#13](https://github.com/XuehaiPan/nvitop/issues/13)

It seems works.

nvitop patch it in PR https://github.com/XuehaiPan/nvitop/pull/30

```python
>>> print(pynvml.nvmlDeviceGetMemoryInfo(h,version=pynvml.nvmlMemory_v2))
c_nvmlMemory_v2_t(version: 33554472 B, total: 25769803776 B, reserved: 322633728 B, free: 25447038976 B, used: 131072 B)
```

**Comment by wookayin** [comment]
I hate NVIDIA breaking existing functions for new versions of drivers. For drivers higher than 510.39.01, perhaps the only way to get the correct memory usage information is to use `nvmlDeviceGetMemoryInfo_v2`, i.e. use `pynvml` 11.510.69+. However, older drivers cannot use `pynvml>=11.510.69` because it breaks process information (#107).

A consequence is that a different pynvml version must be used depending on the ndivida drivers (this is something difficult to resolve during *installation and build time*), and if incompatible versions are found then a proper warning messages should be printed. I'm going to relaxe the pynvml requirement `<= 11.495.46` introduced in v1.0 (#107).

**Comment by wookayin** [comment]
Fixed via https://github.com/wookayin/gpustat/pull/143#issuecomment-1334541103.
