### ISSUE TITLE
gpustat return "error on calling nvidia-smi"?

### ISSUE THREAD

**Issue by yihui-he** [wookayin/gpustat#5]
nvidia-smi works on my machine

**Comment by wookayin** [comment]
Invocation of `nvidia-smi --query-gpu=index,uuid,name,temperature.gpu,utilization.gpu,memory.used,memory.total
 --format=csv,noheader,nounits` might be failed (or, `--query-apps`).

Could you please provide more information, e.g. which version of nvidia driver is used? Or you can modify the code so that the exception `CalledProcessError` is thrown outside?

**Comment by yihui-he** [comment]
```
$ nvidia-smi --query-gpu=index,uuid,name,temperature.gpu,utilization.gpu,memory.used,memory.total --format=csv,noheader,nounits
0, GPU-004f693d-767b-b215-b4a9-a18af0ffd643, GeForce GTX TITAN X, 25, 0, 802, 12206
1, GPU-86fe97db-bf54-a056-4e8d-9b07e1a298e7, GeForce GTX TITAN X, 54, 86, 10032, 12206
2, GPU-2090c509-a97a-e2fe-68f4-cf9e874c36f2, GeForce GTX TITAN X, 55, 85, 6442, 12206
3, GPU-f0e47078-b19f-a3ff-bf2e-03a4c5fe3c2a, GeForce GTX TITAN X, 58, 60, 6442, 12206
4, GPU-637ac0be-f0e1-b056-bf28-b2c046e5e17e, GeForce GTX TITAN X, 55, 84, 6459, 12206
5, GPU-4168500a-bee8-3b4d-ba1b-75289a4afdcd, GeForce GTX TITAN X, 54, 83, 6440, 12206
6, GPU-92ce5025-17c0-7c83-d2eb-a697262d4c46, GeForce GTX TITAN X, 56, 83, 6451, 12206
7, GPU-f199c9ea-65d8-5382-aefe-a9e8fb48057b, GeForce GTX TITAN X, 55, 82, 6442, 12206
```

**Comment by wookayin** [comment]
Closing this issue as you mention that it works on your machine.

Please re-open this if it happens again, and provide some information for debugging (e.g. why process calling failed), please.
